export * from './shared/mod.ts';

export * as v1 from './v1/mod.ts';
export * as v2 from './v2/mod.ts';
export * as v3 from './v3/mod.ts';
export * as v4 from './v4/mod.ts';

export * as external from './external/mod.ts';
export * as wrapper from './wrapper/mod.ts';

export {
   basicEvent as V1BasicEventContainer,
   bombNote as V1BombNoteContainer,
   bpmEvent as V1BPMEventContainer,
   colorBoostEvent as V1ColorBoostEventContainer,
   colorNote as V1ColorNoteContainer,
   compatDifficulty as compatV1Difficulty,
   compatInfo as compatV1Info,
   CustomBookmarkSchema as V1CustomBookmarkSchema,
   CustomBPMChangeOldSchema as V1CustomBPMChangeOldSchema,
   CustomColorObjectSchema as V1CustomColorObjectSchema,
   difficulty as V1DifficultyContainer,
   DifficultySchema as V1DifficultySchema,
   EventSchema as V1EventSchema,
   type GenericJSONFilename as V1GenericJSONFilename,
   type IBaseObject as IV1BaseObject,
   type ICustomDifficulty as IV1CustomDifficulty,
   type ICustomInfo as IV1CustomInfo,
   type ICustomInfoDifficulty as IV1CustomInfoDifficulty,
   type IDifficulty as IV1Difficulty,
   type IEvent as IV1Event,
   type IInfo as IV1Info,
   type IInfoDifficulty as IV1InfoDifficulty,
   info as V1InfoContainer,
   infoBeatmap as V1InfoBeatmapContainer,
   InfoDifficultySchema as V1InfoDifficultySchema,
   InfoSchema as V1InfoSchema,
   type INote as IV1Note,
   type IObstacle as IV1Obstacle,
   NoteSchema as V1NoteSchema,
   obstacle as V1ObstacleContainer,
   ObstacleSchema as V1ObstacleSchema,
   optimizeDifficulty as optimizeV1Difficulty,
   optimizeInfo as optimizeV1Info,
   rotationEvent as V1RotationEventContainer,
} from './v1/mod.ts';

export {
   arc as V2ArcContainer,
   ArcSchema as V2ArcSchema,
   audioData as V2AudioDataContainer,
   basicEvent as V2BasicEventContainer,
   basicEventTypesForKeywords as V2BasicEventTypesForKeywordsContainer,
   basicEventTypesWithKeywords as V2BasicEventTypesWithKeywordsContainer,
   bombNote as V2BombNoteContainer,
   bpmEvent as V2BPMEventContainer,
   BPMInfoRegionSchema as V2BPMInfoRegionSchema,
   BPMInfoSchema as V2BPMInfoSchema,
   colorBoostEvent as V2ColorBoostEventContainer,
   colorNote as V2ColorNoteContainer,
   ColorObjectSchema as V2ColorObjectSchema,
   compatAudioData as compatV2AudioData,
   compatDifficulty as compatV2Difficulty,
   compatInfo as compatV2Info,
   CustomBookmarkSchema as V2CustomBookmarkSchema,
   CustomBPMChangeOldSchema as V2CustomBPMChangeOldSchema,
   CustomBPMChangeSchema as V2CustomBPMChangeSchema,
   CustomColorObjectSchema as V2CustomColorObjectSchema,
   CustomColorSchemeSchema as V2CustomColorSchemeSchema,
   CustomDataDifficultySchema as V2CustomDataDifficultySchema,
   CustomDataInfoSchema as V2CustomDataInfoSchema,
   CustomDataInfoSetDifficultySchema as V2CustomDataInfoSetDifficultySchema,
   CustomDataInfoSetSchema as V2CustomDataInfoSetSchema,
   CustomEditorInfoSchema as V2CustomEditorInfoSchema,
   CustomEditorSchema as V2CustomEditorSchema,
   difficulty as V2DifficultyContainer,
   DifficultySchema as V2DifficultySchema,
   EventSchema as V2EventSchema,
   type IAnimation as IV2Animation,
   type IArc as IV2Arc,
   type IBaseObject as IV2BaseObject,
   type IBookmark as IV2Bookmark,
   type IBPMChange as IV2BPMChange,
   type IBPMChangeOld as IV2BPMChangeOld,
   type IBPMInfo as IV2BPMInfo,
   type IBPMInfoRegion as IV2BPMInfoRegion,
   type IChromaAnimation as IV2ChromaAnimation,
   type IChromaCustomData as IV2ChromaCustomData,
   type IChromaCustomEventDataAnimateTrack as IV2ChromaCustomEventDataAnimateTrack,
   type IChromaCustomEventDataAssignFogTrack as IV2ChromaCustomEventDataAssignFogTrack,
   type IChromaCustomEventDataAssignPathAnimation as IV2ChromaCustomEventDataAssignPathAnimation,
   type IChromaEnvironment as IV2ChromaEnvironment,
   type IChromaEnvironmentBase as IV2ChromaEnvironmentBase,
   type IChromaEnvironmentGeometry as IV2ChromaEnvironmentGeometry,
   type IChromaEnvironmentID as IV2ChromaEnvironmentID,
   type IChromaEventLaser as IV2ChromaEventLaser,
   type IChromaEventLight as IV2ChromaEventLight,
   type IChromaEventRing as IV2ChromaEventRing,
   type IChromaEventZoom as IV2ChromaEventZoom,
   type IChromaGeometry as IV2ChromaGeometry,
   type IChromaGeometryBase as IV2ChromaGeometryBase,
   type IChromaGeometryCustom as IV2ChromaGeometryCustom,
   type IChromaInfoCustomData as IV2ChromaInfoCustomData,
   type IChromaLightGradient as IV2ChromaLightGradient,
   type IChromaMaterial as IV2ChromaMaterial,
   type IChromaNote as IV2ChromaNote,
   type IChromaObstacle as IV2ChromaObstacle,
   type IColorScheme as IV2ColorScheme,
   type ICustomDataDifficulty as IV2CustomDataDifficulty,
   type ICustomDataInfo as IV2CustomDataInfo,
   type ICustomDataInfoDifficulty as IV2CustomDataInfoDifficulty,
   type ICustomDataInfoSet as IV2CustomDataInfoSet,
   type ICustomDataNote as IV2CustomDataNote,
   type ICustomDataObstacle as IV2CustomDataObstacle,
   type ICustomEvent as IV2CustomEvent,
   type ICustomEventAnimateTrack as IV2CustomEventAnimateTrack,
   type ICustomEventAssignFogTrack as IV2CustomEventAssignFogTrack,
   type ICustomEventAssignPathAnimation as IV2CustomEventAssignPathAnimation,
   type ICustomEventAssignPlayerToTrack as IV2CustomEventAssignPlayerToTrack,
   type ICustomEventAssignTrackParent as IV2CustomEventAssignTrackParent,
   type ICustomEventDataAnimateTrack as IV2CustomEventDataAnimateTrack,
   type ICustomEventDataAssignPathAnimation as IV2CustomEventDataAssignPathAnimation,
   type IDifficulty as IV2Difficulty,
   type IEditor as IV2Editor,
   type IEditorInfo as IV2EditorInfo,
   type IEvent as IV2Event,
   type IEventBase as IV2EventBase,
   type IEventBoost as IV2EventBoost,
   type IEventBPMChange as IV2EventBPMChange,
   type IEventExtra as IV2EventExtra,
   type IEventGeneric as IV2EventGeneric,
   type IEventLaneRotation as IV2EventLaneRotation,
   type IEventLaser as IV2EventLaser,
   type IEventLight as IV2EventLight,
   type IEventRing as IV2EventRing,
   type IEventSpecial as IV2EventSpecial,
   type IEventZoom as IV2EventZoom,
   type IHeckBase as IV2HeckBase,
   type IHeckCustomEventDataAnimateTrack as IV2HeckCustomEventDataAnimateTrack,
   type IHeckCustomEventDataAssignPathAnimation as IV2HeckCustomEventDataAssignPathAnimation,
   type IHeckInfoCustomData as IV2HeckInfoCustomData,
   type IInfo as IV2Info,
   type IInfoColorScheme as IV2InfoColorScheme,
   type IInfoColorSchemeData as IV2InfoColorSchemeData,
   type IInfoDifficulty as IV2InfoDifficulty,
   type IInfoSet as IV2InfoSet,
   type IInfoSettingsCustomData as IV2InfoSettingsCustomData,
   type INEAnimation as IV2NEAnimation,
   type INECustomEventDataAnimateTrack as IV2NECustomEventDataAnimateTrack,
   type INECustomEventDataAssignPathAnimation as IV2NECustomEventDataAssignPathAnimation,
   type INECustomEventDataAssignPlayerToTrack as IV2NECustomEventDataAssignPlayerToTrack,
   type INECustomEventDataAssignTrackParent as IV2NECustomEventDataAssignTrackParent,
   type INEEvent as IV2NEEvent,
   type INENote as IV2NENote,
   type INEObstacle as IV2NEObstacle,
   info as V2InfoContainer,
   infoBeatmap as V2InfoBeatmapContainer,
   InfoColorSchemeDataSchema as V2InfoColorSchemeDataSchema,
   InfoColorSchemeSchema as V2InfoColorSchemeSchema,
   InfoSchema as V2InfoSchema,
   InfoSetDifficultySchema as V2InfoSetDifficultySchema,
   InfoSetSchema as V2InfoSetSchema,
   type INote as IV2Note,
   type IObstacle as IV2Obstacle,
   type IPointDefinition as IV2PointDefinition,
   type ISpecialEventsKeywordFilters as IV2SpecialEventsKeywordFilters,
   type ISpecialEventsKeywordFiltersKeywords as IV2SpecialEventsKeywordFiltersKeywords,
   type IVivifyCustomDataInfo as IV2VivifyCustomDataInfo,
   type IWaypoint as IV2Waypoint,
   NoteSchema as V2NoteSchema,
   obstacle as V2ObstacleContainer,
   ObstacleSchema as V2ObstacleSchema,
   optimizeDifficulty as optimizeV2Difficulty,
   optimizeInfo as optimizeV2Info,
   rotationEvent as V2RotationEventContainer,
   SpecialEventsKeywordFiltersKeywordsSchema as V2SpecialEventsKeywordFiltersKeywordsSchema,
   SpecialEventsKeywordFiltersSchema as V2SpecialEventsKeywordFiltersSchema,
   waypoint as V2WaypointContainer,
   WaypointSchema as V2WaypointSchema,
} from './v2/mod.ts';

export {
   arc as V3ArcContainer,
   ArcSchema as V3ArcSchema,
   basicEvent as V3BasicEventContainer,
   BasicEventSchema as V3BasicEventSchema,
   basicEventTypesForKeywords as V3BasicEventTypesForKeywordsContainer,
   BasicEventTypesForKeywordsSchema as V3BasicEventTypesForKeywordsSchema,
   basicEventTypesWithKeywords as V3BasicEventTypesWithKeywordsContainer,
   BasicEventTypesWithKeywordsSchema as V3BasicEventTypesWithKeywordsSchema,
   bombNote as V3BombNoteContainer,
   BombNoteSchema as V3BombNoteSchema,
   BPMChangeEventSchema as V3BPMChangeEventSchema,
   bpmEvent as V3BPMEventContainer,
   chain as V3ChainContainer,
   ChainSchema as V3ChainSchema,
   colorBoostEvent as V3ColorBoostEventContainer,
   ColorBoostEventSchema as V3ColorBoostEventSchema,
   colorNote as V3ColorNoteContainer,
   ColorNoteSchema as V3ColorNoteSchema,
   compatDifficulty as compatV3Difficulty,
   compatLightshow as compatV3Lightshow,
   CustomBookmarkSchema as V3CustomBookmarkSchema,
   CustomBPMChangeSchema as V3CustomBPMChangeSchema,
   CustomDataDifficultySchema as V3CustomDataDifficultySchema,
   difficulty as V3DifficultyContainer,
   DifficultySchema as V3DifficultySchema,
   fxEventBox as V3FXEventBoxContainer,
   fxEventBoxGroup as V3FXEventBoxGroupContainer,
   fxEventFloat as V3FXEventFloatContainer,
   FxEventFloatSchema as V3FxEventFloatSchema,
   fxEventInt as V3FXEventIntContainer,
   FxEventIntSchema as V3FxEventIntSchema,
   FxEventsCollectionSchema as V3FxEventsCollectionSchema,
   type IAnimation as IV3Animation,
   type IArc as IV3Arc,
   type IBaseObject as IV3BaseObject,
   type IBaseSlider as IV3BaseSlider,
   type IBasicEvent as IV3BasicEvent,
   type IBasicEventBase as IV3BasicEventBase,
   type IBasicEventBoost as IV3BasicEventBoost,
   type IBasicEventBPMChange as IV3BasicEventBPMChange,
   type IBasicEventExtra as IV3BasicEventExtra,
   type IBasicEventGeneric as IV3BasicEventGeneric,
   type IBasicEventLaneRotation as IV3BasicEventLaneRotation,
   type IBasicEventLaserRotation as IV3BasicEventLaserRotation,
   type IBasicEventLight as IV3BasicEventLight,
   type IBasicEventRing as IV3BasicEventRing,
   type IBasicEventSpecial as IV3BasicEventSpecial,
   type IBasicEventTypesForKeywords as IV3BasicEventTypesForKeywords,
   type IBasicEventTypesWithKeywords as IV3BasicEventTypesWithKeywords,
   type IBombNote as IV3BombNote,
   type IBookmark as IV3Bookmark,
   type IBPMChange as IV3BPMChange,
   type IBPMEvent as IV3BPMEvent,
   type IChain as IV3Chain,
   type IChromaAnimation as IV3ChromaAnimation,
   type IChromaComponent as IV3ChromaComponent,
   type IChromaComponentBloomFogEnvironment as IV3ChromaComponentBloomFogEnvironment,
   type IChromaComponentLightWithID as IV3ChromaComponentLightWithID,
   type IChromaComponentTubeBloomPrePassLight as IV3ChromaComponentTubeBloomPrePassLight,
   type IChromaCustomData as IV3ChromaCustomData,
   type IChromaCustomEventDataAnimateComponent as IV3ChromaCustomEventDataAnimateComponent,
   type IChromaCustomEventDataAnimateTrack as IV3ChromaCustomEventDataAnimateTrack,
   type IChromaCustomEventDataAssignPathAnimation as IV3ChromaCustomEventDataAssignPathAnimation,
   type IChromaEnvironment as IV3ChromaEnvironment,
   type IChromaEnvironmentBase as IV3ChromaEnvironmentBase,
   type IChromaEnvironmentGeometry as IV3ChromaEnvironmentGeometry,
   type IChromaEnvironmentID as IV3ChromaEnvironmentID,
   type IChromaEventLaser as IV3ChromaEventLaser,
   type IChromaEventLight as IV3ChromaEventLight,
   type IChromaEventRing as IV3ChromaEventRing,
   type IChromaEventZoom as IV3ChromaEventZoom,
   type IChromaGeometry as IV3ChromaGeometry,
   type IChromaGeometryBase as IV3ChromaGeometryBase,
   type IChromaGeometryCustom as IV3ChromaGeometryCustom,
   type IChromaMaterial as IV3ChromaMaterial,
   type IChromaNote as IV3ChromaNote,
   type IChromaObstacle as IV3ChromaObstacle,
   type IColorBoostEvent as IV3ColorBoostEvent,
   type IColorNote as IV3ColorNote,
   type ICustomDataDifficulty as IV3CustomDataDifficulty,
   type ICustomDataNote as IV3CustomDataNote,
   type ICustomDataObstacle as IV3CustomDataObstacle,
   type ICustomDataSlider as IV3CustomDataSlider,
   type ICustomEvent as IV3CustomEvent,
   type ICustomEventAnimateComponent as IV3CustomEventAnimateComponent,
   type ICustomEventAnimateTrack as IV3CustomEventAnimateTrack,
   type ICustomEventAssignObjectPrefab as IV3CustomEventAssignObjectPrefab,
   type ICustomEventAssignPathAnimation as IV3CustomEventAssignPathAnimation,
   type ICustomEventAssignPlayerToTrack as IV3CustomEventAssignPlayerToTrack,
   type ICustomEventAssignTrackParent as IV3CustomEventAssignTrackParent,
   type ICustomEventBase as IV3CustomEventBase,
   type ICustomEventBlit as IV3CustomEventBlit,
   type ICustomEventCreateCamera as IV3CustomEventCreateCamera,
   type ICustomEventCreateScreenTexture as IV3CustomEventCreateScreenTexture,
   type ICustomEventDataAnimateTrack as IV3CustomEventDataAnimateTrack,
   type ICustomEventDataAssignPathAnimation as IV3CustomEventDataAssignPathAnimation,
   type ICustomEventDeclareRenderTexture as IV3CustomEventDeclareRenderTexture,
   type ICustomEventDestroyObject as IV3CustomEventDestroyObject,
   type ICustomEventDestroyTexture as IV3CustomEventDestroyTexture,
   type ICustomEventInstantiatePrefab as IV3CustomEventInstantiatePrefab,
   type ICustomEventSetAnimatorProperty as IV3CustomEventSetAnimatorProperty,
   type ICustomEventSetCameraProperty as IV3CustomEventSetCameraProperty,
   type ICustomEventSetGlobalProperty as IV3CustomEventSetGlobalProperty,
   type ICustomEventSetMaterialProperty as IV3CustomEventSetMaterialProperty,
   type ICustomEventSetRenderingSettings as IV3CustomEventSetRenderingSettings,
   type IDifficulty as IV3Difficulty,
   type IEventBox as IV3EventBox,
   type IEventBoxGroup as IV3EventBoxGroup,
   type IEventBoxGroupContainer as IV3EventBoxGroupContainer,
   type IFxEventBox as IV3FxEventBox,
   type IFxEventBoxGroup as IV3FxEventBoxGroup,
   type IFxEventFloat as IV3FxEventFloat,
   type IFxEventFloatBoxContainer as IV3FxEventFloatBoxContainer,
   type IFxEventInt as IV3FxEventInt,
   type IFxEventsCollection as IV3FxEventsCollection,
   type IGridObject as IV3GridObject,
   type IHeckBase as IV3HeckBase,
   type IHeckCustomData as IV3HeckCustomData,
   type IHeckCustomEventDataAnimateTrack as IV3HeckCustomEventDataAnimateTrack,
   type IHeckCustomEventDataAssignPathAnimation as IV3HeckCustomEventDataAssignPathAnimation,
   type IIndexFilter as IV3IndexFilter,
   type ILightColorEvent as IV3LightColorEvent,
   type ILightColorEventBox as IV3LightColorEventBox,
   type ILightColorEventBoxGroup as IV3LightColorEventBoxGroup,
   type ILightRotationEvent as IV3LightRotationEvent,
   type ILightRotationEventBox as IV3LightRotationEventBox,
   type ILightRotationEventBoxGroup as IV3LightRotationEventBoxGroup,
   type ILightshow as IV3Lightshow,
   type ILightTranslationEvent as IV3LightTranslationEvent,
   type ILightTranslationEventBox as IV3LightTranslationEventBox,
   type ILightTranslationEventBoxGroup as IV3LightTranslationEventBoxGroup,
   indexFilter as V3IndexFilterContainer,
   IndexFilterSchema as V3IndexFilterSchema,
   type INEAnimation as IV3NEAnimation,
   type INECustomEventDataAnimateTrack as IV3NECustomEventDataAnimateTrack,
   type INECustomEventDataAssignPathAnimation as IV3NECustomEventDataAssignPathAnimation,
   type INECustomEventDataAssignPlayerToTrack as IV3NECustomEventDataAssignPlayerToTrack,
   type INECustomEventDataAssignTrackParent as IV3NECustomEventDataAssignTrackParent,
   type INENote as IV3NENote,
   type INEObstacle as IV3NEObstacle,
   type INESlider as IV3NESlider,
   type IObstacle as IV3Obstacle,
   type IPointDefinition as IV3PointDefinition,
   type IRotationEvent as IV3RotationEvent,
   type IVivifyAnimatorProperty as IV3VivifyAnimatorProperty,
   type IVivifyCameraProperty as IV3VivifyCameraProperty,
   type IVivifyCustomEventAssignObjectPrefab as IV3VivifyCustomEventAssignObjectPrefab,
   type IVivifyCustomEventBlit as IV3VivifyCustomEventBlit,
   type IVivifyCustomEventCreateCamera as IV3VivifyCustomEventCreateCamera,
   type IVivifyCustomEventCreateScreenTexture as IV3VivifyCustomEventCreateScreenTexture,
   type IVivifyCustomEventDeclareRenderTexture as IV3VivifyCustomEventDeclareRenderTexture,
   type IVivifyCustomEventDestroyObject as IV3VivifyCustomEventDestroyObject,
   type IVivifyCustomEventDestroyTexture as IV3VivifyCustomEventDestroyTexture,
   type IVivifyCustomEventInstantiatePrefab as IV3VivifyCustomEventInstantiatePrefab,
   type IVivifyCustomEventSetAnimatorProperty as IV3VivifyCustomEventSetAnimatorProperty,
   type IVivifyCustomEventSetCameraProperty as IV3VivifyCustomEventSetCameraProperty,
   type IVivifyCustomEventSetGlobalProperty as IV3VivifyCustomEventSetGlobalProperty,
   type IVivifyCustomEventSetMaterialProperty as IV3VivifyCustomEventSetMaterialProperty,
   type IVivifyCustomEventSetRenderingSettings as IV3VivifyCustomEventSetRenderingSettings,
   type IVivifyMaterialProperty as IV3VivifyMaterialProperty,
   type IWaypoint as IV3Waypoint,
   LightColorBaseSchema as V3LightColorBaseSchema,
   lightColorEvent as V3LightColorEventContainer,
   lightColorEventBox as V3LightColorEventBoxContainer,
   lightColorEventBoxGroup as V3LightColorEventBoxGroupContainer,
   LightColorEventBoxGroupSchema as V3LightColorEventBoxGroupSchema,
   LightColorEventBoxSchema as V3LightColorEventBoxSchema,
   LightRotationBaseSchema as V3LightRotationBaseSchema,
   lightRotationEvent as V3LightRotationEventContainer,
   lightRotationEventBox as V3LightRotationEventBoxContainer,
   lightRotationEventBoxGroup as V3LightRotationEventBoxGroupContainer,
   LightRotationEventBoxGroupSchema as V3LightRotationEventBoxGroupSchema,
   LightRotationEventBoxSchema as V3LightRotationEventBoxSchema,
   lightshow as V3LightshowContainer,
   LightshowSchema as V3LightshowSchema,
   LightTranslationBaseSchema as V3LightTranslationBaseSchema,
   lightTranslationEvent as V3LightTranslationEventContainer,
   lightTranslationEventBox as V3LightTranslationEventBoxContainer,
   lightTranslationEventBoxGroup as V3LightTranslationEventBoxGroupContainer,
   LightTranslationEventBoxGroupSchema as V3LightTranslationEventBoxGroupSchema,
   LightTranslationEventBoxSchema as V3LightTranslationEventBoxSchema,
   obstacle as V3ObstacleContainer,
   ObstacleSchema as V3ObstacleSchema,
   optimizeDifficulty as optimizeV3Difficulty,
   optimizeLightshow as optimizeV3Lightshow,
   rotationEvent as V3RotationEventContainer,
   RotationEventSchema as V3RotationEventSchema,
   VfxEventBoxGroupSchema as V3VfxEventBoxGroupSchema,
   VfxEventBoxSchema as V3VfxEventBoxSchema,
   waypoint as V3WaypointContainer,
   WaypointSchema as V3WaypointSchema,
} from './v3/mod.ts';

export {
   arc as V4ArcContainer,
   ArcSchema as V4ArcSchema,
   audioData as V4AudioDataContainer,
   AudioDataBPMSchema as V4AudioDataBPMSchema,
   AudioDataLUFSSchema as V4AudioDataLUFSSchema,
   AudioDataSchema as V4AudioDataSchema,
   basicEvent as V4BasicEventContainer,
   BasicEventSchema as V4BasicEventSchema,
   bombNote as V4BombNoteContainer,
   BombNoteSchema as V4BombNoteSchema,
   chain as V4ChainContainer,
   ChainSchema as V4ChainSchema,
   colorBoostEvent as V4ColorBoostEventContainer,
   ColorBoostEventSchema as V4ColorBoostEventSchema,
   colorNote as V4ColorNoteContainer,
   ColorNoteSchema as V4ColorNoteSchema,
   compatAudioData as compatV4AudioData,
   compatDifficulty as compatV4Difficulty,
   compatInfo as compatV4Info,
   compatLightshow as compatV4Lightshow,
   CustomCharacteristicSchema as V4CustomCharacteristicSchema,
   CustomDataInfoBeatmapSchema as V4CustomDataInfoBeatmapSchema,
   CustomDataInfoSchema as V4CustomDataInfoSchema,
   difficulty as V4DifficultyContainer,
   DifficultySchema as V4DifficultySchema,
   EventBoxGroupSchema as V4EventBoxGroupSchema,
   EventBoxSchema as V4EventBoxSchema,
   fxEventBox as V4FXEventBoxContainer,
   fxEventBoxGroup as V4FXEventBoxGroupContainer,
   FXEventBoxSchema as V4FXEventBoxSchema,
   fxEventFloat as V4FXEventFloatContainer,
   FXEventFloatSchema as V4FXEventFloatSchema,
   type IArc as IV4Arc,
   type IArcContainer as IV4ArcContainer,
   type IAudio as IV4Audio,
   type IAudioBPM as IV4AudioBPM,
   type IAudioLUFS as IV4AudioLUFS,
   type IBasicEvent as IV4BasicEvent,
   type IBasicEventBase as IV4BasicEventBase,
   type IBasicEventBoost as IV4BasicEventBoost,
   type IBasicEventBPMChange as IV4BasicEventBPMChange,
   type IBasicEventContainer as IV4BasicEventContainer,
   type IBasicEventExtra as IV4BasicEventExtra,
   type IBasicEventGeneric as IV4BasicEventGeneric,
   type IBasicEventLaneRotation as IV4BasicEventLaneRotation,
   type IBasicEventLaserRotation as IV4BasicEventLaserRotation,
   type IBasicEventLight as IV4BasicEventLight,
   type IBasicEventRing as IV4BasicEventRing,
   type IBasicEventSpecial as IV4BasicEventSpecial,
   type IBombNote as IV4BombNote,
   type IBombNoteContainer as IV4BombNoteContainer,
   type IChain as IV4Chain,
   type IChainContainer as IV4ChainContainer,
   type IColorBoostEvent as IV4ColorBoostEvent,
   type IColorBoostEventContainer as IV4ColorBoostEventContainer,
   type IColorNote as IV4ColorNote,
   type IColorNoteContainer as IV4ColorNoteContainer,
   type ICustomCharacteristic as IV4CustomCharacteristic,
   type ICustomDataInfo as IV4CustomDataInfo,
   type ICustomDataInfoBeatmap as IV4CustomDataInfoBeatmap,
   type IDifficulty as IV4Difficulty,
   type IEventBox as IV4EventBox,
   type IEventBoxCommon as IV4EventBoxCommon,
   type IEventBoxGroup as IV4EventBoxGroup,
   type IEventBoxGroupContainer as IV4EventBoxGroupContainer,
   type IFxEventBox as IV4FxEventBox,
   type IFxEventFloat as IV4FxEventFloat,
   type IFxEventFloatBoxContainer as IV4FxEventFloatBoxContainer,
   type IFxEventFloatContainer as IV4FxEventFloatContainer,
   type IGrid as IV4Grid,
   type IIndexFilter as IV4IndexFilter,
   type IInfo as IV4Info,
   type IInfoAudio as IV4InfoAudio,
   type IInfoBeatmap as IV4InfoBeatmap,
   type IInfoBeatmapAuthors as IV4InfoBeatmapAuthors,
   type IInfoColorScheme as IV4InfoColorScheme,
   type IInfoSong as IV4InfoSong,
   type IItem as IV4Item,
   type ILightColorBoxContainer as IV4LightColorBoxContainer,
   type ILightColorEvent as IV4LightColorEvent,
   type ILightColorEventBox as IV4LightColorEventBox,
   type ILightColorEventContainer as IV4LightColorEventContainer,
   type ILightRotationBoxContainer as IV4LightRotationBoxContainer,
   type ILightRotationEvent as IV4LightRotationEvent,
   type ILightRotationEventBox as IV4LightRotationEventBox,
   type ILightRotationEventContainer as IV4LightRotationEventContainer,
   type ILightshow as IV4Lightshow,
   type ILightTranslationBoxContainer as IV4LightTranslationBoxContainer,
   type ILightTranslationEvent as IV4LightTranslationEvent,
   type ILightTranslationEventBox as IV4LightTranslationEventBox,
   type ILightTranslationEventContainer as IV4LightTranslationEventContainer,
   indexFilter as V4IndexFilterContainer,
   IndexFilterSchema as V4IndexFilterSchema,
   info as V4InfoContainer,
   InfoAudioSchema as V4InfoAudioSchema,
   infoBeatmap as V4InfoBeatmapContainer,
   InfoBeatmapAuthorsSchema as V4InfoBeatmapAuthorsSchema,
   InfoColorSchemeSchema as V4InfoColorSchemeSchema,
   InfoDifficultySchema as V4InfoDifficultySchema,
   InfoSchema as V4InfoSchema,
   InfoSongSchema as V4InfoSongSchema,
   type INJSEvent as IV4NJSEvent,
   type INjsEventContainer as IV4NJSEventContainer,
   type IObject as IV4Object,
   type IObjectArc as IV4ObjectArc,
   type IObjectChain as IV4ObjectChain,
   type IObjectLane as IV4ObjectLane,
   type IObstacle as IV4Obstacle,
   type IObstacleContainer as IV4ObstacleContainer,
   type ISpawnRotation as IV4SpawnRotation,
   type ISpawnRotationContainer as IV4SpawnRotationContainer,
   type IWaypoint as IV4Waypoint,
   type IWaypointContainer as IV4WaypointContainer,
   lightColorEvent as V4LightColorEventContainer,
   lightColorEventBox as V4LightColorEventBoxContainer,
   lightColorEventBoxGroup as V4LightColorEventBoxGroupContainer,
   LightColorEventBoxSchema as V4LightColorEventBoxSchema,
   LightColorEventSchema as V4LightColorEventSchema,
   lightRotationEvent as V4LightRotationEventContainer,
   lightRotationEventBox as V4LightRotationEventBoxContainer,
   lightRotationEventBoxGroup as V4LightRotationEventBoxGroupContainer,
   LightRotationEventBoxSchema as V4LightRotationEventBoxSchema,
   LightRotationEventSchema as V4LightRotationEventSchema,
   lightshow as V4LightshowContainer,
   LightshowSchema as V4LightshowSchema,
   lightTranslationEvent as V4LightTranslationEventContainer,
   lightTranslationEventBox as V4LightTranslationEventBoxContainer,
   lightTranslationEventBoxGroup as V4LightTranslationEventBoxGroupContainer,
   LightTranslationEventBoxSchema as V4LightTranslationEventBoxSchema,
   LightTranslationEventSchema as V4LightTranslationEventSchema,
   njsEvent as V4NJSEventContainer,
   NJSEventSchema as V4NJSEventSchema,
   ObjectArcSchema as V4ObjectArcSchema,
   ObjectChainSchema as V4ObjectChainSchema,
   ObjectLaneSchema as V4ObjectLaneSchema,
   ObjectSchema as V4ObjectSchema,
   obstacle as V4ObstacleContainer,
   ObstacleSchema as V4ObstacleSchema,
   optimizeDifficulty as optimizeV4Difficulty,
   optimizeInfo as optimizeV4Info,
   optimizeLightshow as optimizeV4Lightshow,
   rotationEvent as V4RotationEventContainer,
   SpawnRotationSchema as V4SpawnRotationSchema,
   waypoint as V4WaypointContainer,
   WaypointSchema as V4WaypointSchema,
} from './v4/mod.ts';

export * from './external/mod.ts';
export * from './wrapper/mod.ts';
