export enum ChromaEnvironmentAbbreviation {
   duplicate = 'D',
   active = 'A',
   scale = 'S',
   position = 'P',
   localPosition = 'Lp',
   rotation = 'R',
   localRotation = 'Lr',
   lightID = 'Li',
   track = 'T',
}

export enum NEDataAbbreviation {
   childrenTracks = 'Ct',
   color = 'C',
   definitePosition = 'Dp',
   dissolve = 'D',
   dissolveArrow = 'Da',
   duration = 'Dur',
   easing = 'E',
   interactable = 'I',
   localRotation = 'Lr',
   parentTrack = 'Pt',
   position = 'P',
   rotation = 'R',
   scale = 'S',
   time = 'T',
   track = 'Tr',
   worldPositionStays = 'Wps',
}
